#!/bin/sh
# fxgasm_cross.sh CC "CFLAGS" - write fxgasm.h and fxinline.h for the TARGET.
#
# [retro3dfx] fxgasm.c prints struct offsets by RUNNING it, so a cross build
# runs it on the BUILD host. On a 64-bit Linux host that is a 64-bit program:
# every pointer in GrGC is 8 bytes, and all 50 GC offsets the asm triangle
# setup reads come out wrong (fifoPtr 0xe40 instead of 0xe0c, kTriProcOffset
# 0x95c0 instead of 0x9558 - measured 2026-09-25 against the same fxgasm.c
# compiled by i686-w64-mingw32-gcc and run on the Voodoo 5 6000 box). The C
# triangle-setup build never reads these, which is why it went unnoticed.
#
# Instead, compile fxgasm.c with the TARGET compiler to assembly only - the
# Linux asm-offsets technique: each OFFSET() becomes an "i" operand that gcc
# must resolve at compile time, emitted as a marker line, and read back here.
# Nothing has to execute, so no 32-bit libc, Wine or Windows box is needed.
set -e
CC="$1"; CFLAGS="$2"
T=fxgasm_x.c
# everything before main() - the headers, statics and macro definitions
awk '/^main \(/{exit} {buf[++n]=$0} END{for(i=1;i<=n;i++) if(!(i==n && buf[i]=="int")) print buf[i]}' fxgasm.c | \
    sed -e '/^#define OFFSET(/,/^$/d' -e '/^#define OFFSET2(/,/^$/d' -e '/^#define SIZEOF(/,/^$/d' \
        -e '/^#define NEWLINE/d' -e '/^#define COMMENT/d' -e '/^#define HEADER/,/^$/d' > $T
cat >> $T <<'EOC'
void fxgasm_cross_emit(void)
{
    static struct _GlideRoot_s gr;
    static GrGC gc;
#if !GLIDE_HW_TRI_SETUP
    static SstRegs sst;
    static struct dataList_s dl;
#endif
#define OFFSET(p,o,pname) __asm__ volatile ("\n#@@ %c0 " pname :: "i" (__builtin_offsetof(__typeof__(p), o)))
#define SIZEOF(p,pname) __asm__ volatile ("\n#@@ %c0 SIZEOF_" pname :: "i" (sizeof(p)))
#define printf(...) ((void)0)
#define NEWLINE ((void)0)
#define COMMENT ((void)0)
#define HEADER(str) ((void)0)
    {
        int hex = 1; (void) hex;
#include "fxgasm_body.inc"
    }
    __asm__ volatile ("\n#@I kTriProcOffset %c0" :: "i" (__builtin_offsetof(struct GrGC_s, triSetupProc)));
    __asm__ volatile ("\n#@I kInternalFogTableEntryCount %c0" :: "i" (sizeof(((SstRegs *)0)->fogTable) >> 1));
    __asm__ volatile ("\n#@I kTLSOffset %c0" :: "i" (__builtin_offsetof(struct _GlideRoot_s, tlsOffset)));
    __asm__ volatile ("\n#@I kLostContextOffset %c0" :: "i" (__builtin_offsetof(GrGC, lostContext)));
}
EOC
# the OFFSET() calls of main(), after its -inline early return
awk '/^[ \t]*hex = 1;/{f=1; skip=1; next} f&&skip&&/^[ \t]*}[ \t]*$/{skip=0; next} f&&/^    return 0;/{exit} f&&!skip' fxgasm.c > fxgasm_body.inc
# shellcheck disable=SC2086
$CC $CFLAGS -O0 -S -o fxgasm_x.s $T
grep -q '^#@@' fxgasm_x.s || { echo "fxgasm_cross: no offsets emitted" >&2; exit 1; }
{
  printf '\n;----------------------------------------------------------------------\n'
  printf '; Assembler offsets for GC struct (generated by fxgasm_cross.sh for the TARGET)\n'
  printf ';----------------------------------------------------------------------\n\n'
  sed -n 's/^#@@ \([0-9]*\) \(.*\)$/\1 \2/p' fxgasm_x.s | \
    while read -r v n; do printf '%s\tequ %08xh\n' "$n" "$v"; done
} > fxgasm.h
{
  printf '#ifndef __FX_INLINE_H__\n#define __FX_INLINE_H__\n\n'
  sed -n 's/^#@I \([A-Za-z]*\) \([0-9]*\)$/\1 \2/p' fxgasm_x.s | while read -r n v; do
    case $n in
      kInternalFogTableEntryCount) printf '/* The # of 2-byte entries in the hw fog table */\n#define %s 0x%X\n' "$n" "$v" ;;
      kLostContextOffset) printf '#define %s 0x%xUL\n' "$n" "$v" ;;
      *) printf '#define %s 0x%XUL\n' "$n" "$v" ;;
    esac
  done
  printf '\n#endif /* __FX_INLINE_H__ */\n'
} > fxinline.h
rm -f $T fxgasm_x.s fxgasm_body.inc
